@startuml

/'
図の中で目立たせたいエンティティに着色するための
色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define ALREADY_EXISTS_COLOR AAFFAA
!define NEW_COLOR FFAA00

/'
デフォルトのスタイルを設定します。
この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}

package "メモ帳API" as target_system {

    ' メモを予約するためのテーブル 
    entity "memos" as memos <<M,ALREADY_EXISTS_COLOR>> {
        + id [PK]
        --
	`title`: 
	content: 
	created_at: datetime
	updated_at: datetime
    }

    note left of memos : タイトル+内容で保存する。最初はログインなども何も入れないものとします。
}

@enduml
