@startuml

/'
図の中で目立たせたいエンティティに着色するための
色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define ALREADY_EXISTS_COLOR AAFFAA
!define NEW_COLOR FFAA00

/'
デフォルトのスタイルを設定します。
この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}

package "英語面談予約システム" as target_system {

    ' 面談予約される講師側の人の情報を保存している
    entity "mentors" as mentors <<M,ALREADY_EXISTS_COLOR>> {
        + id   [PK]
        --
	name
	introduce
	email
	created_at
	updated_at
    }

    ' 面談予約する側の人の情報を保存している
    entity "mentees" as mentees <<M,ALREADY_EXISTS_COLOR>> {
        + id   [PK]
	name
	introduce
	email
	created_at
	updated_at
    }

    ' 面談予約した時にいつ予約されているのかを保存している
    ' 予約時間の単位については、15min, 30min, 45min, 60min を想定
    entity "reservations" as reservations <<M,ALREADY_EXISTS_COLOR>> {
	+ id [PK]
	# mentor_id [FK]
	# mentee_id [FK]
	# duration_id [FK]
	start_at
	end_at
	created_at
	updated_at
    }

    entity "durations" as durations <<M,ALREADY_EXISTS_COLOR>> {
	+id [PK]
	unit_time  
	created_at
	updated_at
    }

    note left of mentees : 英語の面談予約をする側のこと
}

mentors o-do-o{ reservations
mentees o-do-o{ reservations

@enduml
